from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image, Table, TableStyle, KeepTogether
from reportlab.lib import colors

ROOT=Path(__file__).parent; OUT=ROOT/'output'/'BPIT_API_Gateway_Attendance_Management_Report_Vidhatri_Nautiyal.pdf'; A=ROOT/'tmp'/'report-assets'
OUT.parent.mkdir(exist_ok=True)
styles=getSampleStyleSheet()
body=ParagraphStyle('body', parent=styles['BodyText'], fontName='Times-Roman', fontSize=12, leading=18, alignment=TA_JUSTIFY, firstLineIndent=18, spaceAfter=8)
h1=ParagraphStyle('h1', parent=styles['Heading1'], fontName='Times-Bold', fontSize=14, leading=18, alignment=TA_CENTER, spaceBefore=14, spaceAfter=9)
h2=ParagraphStyle('h2', parent=styles['Heading2'], fontName='Times-Bold', fontSize=12, leading=15, underlineWidth=0.5, spaceBefore=10, spaceAfter=6)
center=ParagraphStyle('center', parent=body, alignment=TA_CENTER, firstLineIndent=0)
small=ParagraphStyle('small', parent=body, fontSize=10, leading=13, firstLineIndent=0)
def P(t,s=body): return Paragraph(t,s)
def page(canvas, doc):
    if doc.page>=9:
        canvas.setFont('Times-Roman',10); canvas.drawCentredString(A4[0]/2,0.55*inch,str(doc.page-8))
def chapter(n,t): return [P(f'CHAPTER {n}<br/>{t.upper()}',h1)]
story=[]
# Cover
story += [Spacer(1,0.55*inch),P('BPIT API GATEWAY BASED<br/>ATTENDANCE MANAGEMENT SYSTEM',ParagraphStyle('cover',parent=center,fontName='Times-Bold',fontSize=17,leading=23)),Spacer(1,0.6*inch),P('Summer Training Report submitted in partial fulfilment of the<br/>requirement for the degree of<br/><br/><b>B.Tech</b><br/><br/>in<br/><br/>Computer Science and Engineering',ParagraphStyle('cover2',parent=center,fontSize=14,leading=20)),Spacer(1,0.32*inch),P('<b>BPIT</b>',ParagraphStyle('bpit',parent=center,fontName='Times-Bold',fontSize=30)),Spacer(1,0.3*inch)]
t=Table([[P('<b>Training Coordinator</b>',center),P('<b>Submitted by</b>',center)],[P('<b>Prof. Achal Kaushik</b><br/>Dean and HOD, CSE Department, BPIT',center),P('<b>Vidhatri Nautiyal</b>',center)]],colWidths=[3.05*inch,3.05*inch]); t.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LINEBELOW',(0,0),(-1,0),0.25,colors.white),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8)])); story += [t,Spacer(1,0.65*inch),P('Bhagwan Parshuram Institute of Technology<br/>PSP-4, Sector-17, Rohini, Delhi - 110089<br/><br/>September 2026',center),PageBreak()]
# front
story += [P('DECLARATION',h1),P('I, Vidhatri Nautiyal, certify that this report entitled "BPIT API Gateway Based Attendance Management System" is submitted in partial fulfilment of the requirement for the award of the degree of B.Tech in Computer Science and Engineering at Bhagwan Parshuram Institute of Technology, GGSIP University. The work presented here is my original work. All material and ideas drawn from other sources have been acknowledged in the text.'),Spacer(1,0.5*inch),P('<b>Date: ____________________                                      Vidhatri Nautiyal</b>',body),PageBreak()]
story += [P('ACKNOWLEDGEMENT',h1),P('I express my sincere gratitude to Prof. Achal Kaushik, Dean and Head of the Department of Computer Science and Engineering, BPIT, for guidance and support throughout this project. His direction helped me shape the work into a practical academic attendance solution.'),P('I also thank the faculty members, classmates, and everyone who provided feedback during development and testing. Their suggestions helped improve the usability of the dashboard, attendance workflows, and clarity of the system design.'),P('Finally, I thank my family for their continued encouragement and support during the training period.'),PageBreak()]
story += [P('COMPANY CERTIFICATE',h1),P('This page is reserved for the signed certificate issued by the training organization, as required by the prescribed summer training report format.',body),PageBreak(),P('TRAINING COORDINATOR CERTIFICATE',h1),P('This is to certify that the report entitled "BPIT API Gateway Based Attendance Management System" submitted by Vidhatri Nautiyal in partial fulfilment of the requirement for the award of the degree of B.Tech in Computer Science and Engineering at BPIT, GGSIP University, is a record of the candidate\'s work and is prepared in accordance with the prescribed format.'),Spacer(1,0.5*inch),P('<b>Date: ____________________                                      Prof. Achal Kaushik<br/>                                                                            Dean and HOD, CSE Department, BPIT</b>'),PageBreak()]
toc=['Abstract','Chapter 1 Introduction','Chapter 2 Software Requirements Specification','Chapter 3 System Design','Chapter 4 Implementation','Chapter 5 Results and Testing','Chapter 6 Comparison and Analysis','Chapter 7 Conclusion and Future Scope','References']
story += [P('TABLE OF CONTENTS',h1)]+[P(x,body) for x in toc]+[PageBreak(),P('LIST OF FIGURES AND TABLES',h1),P('Fig. 3.1 System Architecture<br/>Fig. 3.2 Core Attendance Data Model<br/>Fig. 3.3 Attendance Recording Workflow<br/>Table 2.1 Functional Requirements<br/>Table 5.1 Smoke Test Summary',body),PageBreak()]
story += [P('ABSTRACT',h1),P('This report presents the design and implementation of an attendance management system built on top of the BPIT API Gateway. The system addresses the need for a secure, role-aware platform through which students can view academic information and attendance, while teachers can record attendance and review class-level performance. Administrators manage users, roles, and account status. The application uses an Express.js gateway, a MySQL database accessed through Sequelize, and a browser dashboard implemented with HTML, CSS, and JavaScript.'),P('A central objective was to separate authentication and authorization from attendance operations. Local credentials and optional Microsoft sign-in are normalized into a common JWT session. Role-based access control grants only the permissions needed by each user type. Attendance records are validated against the student\'s enrolled branch, section, semester, and subject catalogue. The project also provides subject-wise attendance summaries with a 75 percent examination-bar indicator.'),P('Automated smoke testing verified most planned workflows while highlighting authorization scenarios that require correction before production deployment. The resulting system demonstrates a maintainable academic gateway with secure access, structured data, and attendance reporting.'),PageBreak()]
story += chapter(1,'Introduction')+[P('<b>Background</b>',h2),P('Attendance is an important academic record because it supports teaching management, student engagement, and institutional compliance. Manual registers are difficult to consolidate and do not provide immediate insight into subject-wise attendance or students falling below the required threshold.'),P('<b>Problem Statement</b>',h2),P('The project addresses the need for a unified gateway that protects attendance services while serving students, teachers, and administrators with different privileges. The system must authenticate users securely, restrict attendance actions by role, associate records with a student\'s academic context, and provide attendance summaries without exposing another student\'s information.'),P('<b>Objectives</b>',h2),P('The objectives are to build common authentication, implement role-based access control, create attendance recording and analysis workflows, model academic timetables and batches, and provide a browser dashboard with protected REST APIs.'),PageBreak()]
rows=[[P('<b>User</b>',small),P('<b>Requirement</b>',small),P('<b>System Response</b>',small)],[P('Student',small),P('View own profile, timetable, and attendance summary',small),P('Limits access to the caller\'s academic context.',small)],[P('Teacher',small),P('Mark attendance and review class performance',small),P('Checks permission and validates subject data.',small)],[P('Administrator',small),P('Manage users, roles, and account status',small),P('Applies privileged permissions.',small)]]
tab=Table(rows,colWidths=[1.1*inch,2.35*inch,2.65*inch]); tab.setStyle(TableStyle([('GRID',(0,0),(-1,-1),0.3,colors.grey),('BACKGROUND',(0,0),(-1,0),colors.lightgrey),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
story += chapter(2,'Software Requirements Specification')+[P('The backend uses Node.js with Express 4. The database layer uses Sequelize 6 and mysql2. JSON Web Tokens are implemented with jose and jsonwebtoken. The client interface uses static HTML, CSS, and vanilla JavaScript.'),tab,P('Table 2.1 Functional Requirements',center),P('<b>Non Functional Requirements</b>',h2),P('Security is provided through scrypt password hashing, signed JWTs, expiry, and account-status checks. Maintainability follows a route-service-model structure. Reliability is supported by validation, structured errors, and a health endpoint.'),PageBreak()]
story += chapter(3,'System Design')+[P('The browser dashboard sends requests to the Express gateway. Public routes allow registration, login, the health check, and the dashboard shell. Protected routes apply authentication and permissions at the route level. The gateway reads and writes the MySQL data model and forwards authenticated requests to a configured attendance microservice when required.'),Image(str(A/'architecture.png'),width=6.1*inch,height=2.36*inch),P('Fig. 3.1 System Architecture',center),P('Identity, role assignment, subjects, timetable slots, and attendance records are independent model concerns. Attendance stores subject, date, status, and a copy of branch, section, and semester, preserving class context even after student movement.'),Image(str(A/'data-model.png'),width=6.1*inch,height=2.36*inch),P('Fig. 3.2 Core Attendance Data Model',center),PageBreak(),P('When a teacher submits attendance, the gateway verifies the bearer token, confirms manage-attendance permission, validates the student and subject, and either creates or updates the record for the student, subject, and date.'),Image(str(A/'workflow.png'),width=6.1*inch,height=2.36*inch),P('Fig. 3.3 Attendance Recording Workflow',center),PageBreak()]
story += chapter(4,'Implementation')+[P('The project separates configuration, routes, services, middleware, data, and Sequelize database models. server.js configures middleware, public endpoints, API route groups, proxy routes, and error handling. The authentication middleware creates and verifies issuer-pinned JWTs, then confirms the account remains active.'),P('Local registration uses per-user salt with scrypt hashing and constant-time password comparison. Password rules require at least eight characters including a letter and digit. Local and Microsoft sign-in create one gateway-token format containing the user identifier, roles, and permissions.'),P('Attendance endpoints provide record listing, individual marking, and bulk class marking. The service permits PRESENT, ABSENT, and LATE status values. Subject codes are checked against the student\'s branch and semester. Library and enrichment periods are excluded from attendance.'),PageBreak()]
rows=[[P('<b>Test execution</b>',small),P('<b>Result</b>',small),P('<b>Interpretation</b>',small)],[P('10 September 2026',small),P('78 passed; 5 failed',small),P('Most core flows operated as intended.',small)],[P('Authentication and account lifecycle',small),P('Passed',small),P('Registration, login, and inactive-account handling verified.',small)],[P('Attendance authorization',small),P('Some failures',small),P('Student privileges require correction in selected routes.',small)],[P('Timetable and class analytics',small),P('Some failures',small),P('Class access controls require correction.',small)]]
tab=Table(rows,colWidths=[1.75*inch,1.25*inch,3.1*inch]); tab.setStyle(TableStyle([('GRID',(0,0),(-1,-1),0.3,colors.grey),('BACKGROUND',(0,0),(-1,0),colors.lightgrey),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]))
story += chapter(5,'Results and Testing')+[P('The repository contains an automated smoke-test script that starts the application on a test port and exercises real HTTP endpoints. It evaluates registration, login, tokens, role restrictions, attendance operations, account deactivation, proxy failure handling, timetable access, enrolment, and analytics.'),tab,P('Table 5.1 Smoke Test Summary',center),P('The application completed the majority of automated checks. Confirmed behaviours include protected-route token validation, account deactivation, teacher attendance marking, idempotent re-marking, invalid-subject rejection, schedule retrieval, enrolment validation, attendance summaries, and upstream-proxy error handling.'),P('Five checks failed during the latest execution. A student could access selected teacher-level attendance, class-view, or cross-class timetable behaviours that should be restricted. These findings are recorded transparently and require priority correction before production deployment.'),PageBreak()]
story += chapter(6,'Comparison and Analysis')+[P('The system concentrates cross-cutting security in the gateway rather than duplicating authentication logic inside attendance routes. It uses a scalable many-to-many role and permission model, validates attendance against academic data, and retains class context in attendance records. The timetable model supports batch-aware laboratory schedules and subject-specific reporting.'),P('Current limitations include focus on the first-year semester-one catalogue and outstanding authorization defects. Production use would need central audit logging, deployment configuration, monitoring, backup procedures, and a full security review.'),PageBreak()]
story += chapter(7,'Conclusion and Future Scope')+[P('The BPIT API Gateway Based Attendance Management System demonstrates how an academic attendance application can combine a protected API gateway, role-based access control, academic validation, and user-facing attendance views. The successful test results show that most planned workflows are in place, while the failed authorization cases clearly identify the next critical improvements.'),P('Future work includes correcting authorization boundaries and adding regression tests; extending curriculum support to all programmes and semesters; adding downloadable reports, notifications, and leave workflows; and introducing audit logs, rate limiting, refresh-token rotation, and deployment monitoring.'),PageBreak(),P('REFERENCES',h1),P('Node.js Foundation. Node.js Documentation. https://nodejs.org/<br/><br/>Express.js. Express Web Framework Documentation. https://expressjs.com/<br/><br/>Sequelize. Sequelize Documentation. https://sequelize.org/<br/><br/>MySQL. MySQL Reference Manual. https://dev.mysql.com/doc/',body)]
SimpleDocTemplate(str(OUT),pagesize=A4,leftMargin=1.25*inch,rightMargin=1.25*inch,topMargin=1*inch,bottomMargin=1*inch,title='BPIT API Gateway Based Attendance Management System',author='Vidhatri Nautiyal').build(story,onFirstPage=page,onLaterPages=page)
print(OUT)
